# Generated by Django 5.2.15 on 2026-08-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allerrors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_id', models.CharField(max_length=300)),
                ('error_msg', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=40)),
                ('ip', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'allerrors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=35)),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('profile', models.CharField(max_length=2000)),
                ('user_type', models.CharField(max_length=5)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'all_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SfsBp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('share', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('fviews', models.IntegerField()),
                ('flikes', models.IntegerField()),
                ('fdownloads', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('fshare', models.IntegerField()),
                ('zipfiles', models.CharField(max_length=250)),
                ('sfs_link', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=30)),
                ('preview1', models.CharField(max_length=40)),
                ('preview2', models.CharField(max_length=40)),
                ('preview3', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=20)),
                ('bp_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('ip', models.CharField(max_length=50)),
                ('feature', models.BooleanField(default=0)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sfs_bp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SfsBpCat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bp_category', models.CharField(max_length=20)),
                ('bp_name', models.CharField(max_length=35)),
                ('bp_img', models.CharField(max_length=30)),
                ('bp_para', models.TextField()),
                ('category_id', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=11)),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sfs_bp_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SfsBpDlv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('bp_pla_id', models.CharField(max_length=35)),
                ('download_type', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sfs_bp_dlv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SfsComments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=40)),
                ('blueprint_id', models.CharField(max_length=40)),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sfs_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=40)),
                ('activity_id', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=10)),
                ('platform_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'total_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BPImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_user', to='sfs.sfsbp', to_field='bp_id')),
            ],
            options={
                'db_table': 'sfs_images',
                'managed': True,
            },
        ),
    ]
