REPORT zclass.

CLASS EMP DEFINITION.
PRIVATE SECTION.
DATA : EMPID TYPE I,
EMPNAME TYPE STRING,
EMPSAL TYPE I.

METHODS
  CONSTRUCTOR IMPORTING  IN_EMPID TYPE I IN_EMPNAME TYPE STRING IN_EMPSAL TYPE I. 
METHODS:
   GET_EMP_DETAILS .

ENDCLASS.
CLASS EMP IMPLEMENTATION

METHOD CONSTRUCTOR.
EMPID = IN_EMPID.
EMPNAME = IN_EMPNAME.
EMPSAL = IN_EMPSAL.
ENDMETHOD.


METHOD GET_EMP_DETAILS.


WRITE : EMPID , EMPNAME , EMPSAL.
ENDMETHOD.
ENDCLASS.


START-OF-SELECTION.


DATA EMP1  TYPE REF TO EMP.
CREATE OBJECT EMP1   EXPORTING  IN_EMPID = 103 IN_EMPNAME = 'SMITH' IN_EMPSAL = 80000 .
EMP1->GET_EMP_DETAILS( ).