# Generated by Django 5.2.15 on 2026-08-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAAProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'aaaaa_product_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AAAUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=12)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(default='user', max_length=10)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'aaaaa_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AAAProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='aaaaa.aaaproductcategory', to_field='category_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='aaaaa.aaausers', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaaa_products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AAAproductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('image_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='aaaaa.aaaproducts', to_field='product_id')),
            ],
            options={
                'db_table': 'aaaaa_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AAAProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='productsDetails', to='aaaaa.aaaproducts', to_field='product_id')),
            ],
            options={
                'db_table': 'aaaaa_product_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AAAOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=50)),
                ('combiner_key', models.CharField(default=0, max_length=50)),
                ('status', models.CharField(max_length=12)),
                ('ship_status', models.CharField(default='pending', max_length=15)),
                ('ship_info', models.CharField(default='nt', max_length=10)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='aaaaa.aaaproducts', to_field='product_id')),
            ],
            options={
                'db_table': 'aaaaa_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AAAUserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('address_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='aaaaa.aaausers', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaaa_user_addresses',
                'managed': True,
            },
        ),
    ]
