# Generated by Django 5.2.17 on 2026-10-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABAPExercise',
            fields=[
                ('exercise_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Beginner', 'Beginner: Syntax, Types, Control Flow'), ('Intermediate', 'Intermediate: Internal Tables, SQL, Modularization'), ('Advanced', 'Advanced: OO ABAP, CDS, RAP, OData')], default='Beginner', max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('topic', models.CharField(default='Basic Syntax', max_length=100)),
                ('problem_statement', models.TextField()),
                ('starter_code', models.TextField()),
                ('solution_hint', models.TextField(blank=True)),
                ('supported_mode', models.CharField(choices=[('simulator', 'Simulator Only'), ('sap_only', 'SAP System Only'), ('both', 'Simulator & Real SAP')], default='simulator', max_length=20)),
                ('points', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'abap_exercises',
                'ordering': ['order', 'created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ABAPLearningProgress',
            fields=[
                ('progress_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('completed_exercises', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='abap_progress', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'abap_learning_progress',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ABAPProject',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('package_name', models.CharField(default='$TMP', max_length=30)),
                ('execution_mode', models.CharField(choices=[('simulator', 'Educational ABAP Simulator'), ('sap_connected', 'Real SAP ABAP System')], default='simulator', max_length=20)),
                ('sap_system_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='abap_projects', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'abap_projects',
                'ordering': ['-updated_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ABAPDictionaryTable',
            fields=[
                ('table_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('delivery_class', models.CharField(default='A', max_length=1)),
                ('fields_schema', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_tables', to='skiltrix.abapproject')),
            ],
            options={
                'db_table': 'abap_dictionary_tables',
                'ordering': ['table_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ABAPSourceFile',
            fields=[
                ('file_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(choices=[('report', 'Executable Report (PROG)'), ('include', 'ABAP Include (INCL)'), ('class', 'ABAP Class (CLAS)'), ('interface', 'ABAP Interface (INTF)'), ('function_module', 'Function Module (FUNC)'), ('ddic_table', 'Dictionary Table (TABL)'), ('structure', 'Dictionary Structure (STRU)')], default='report', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='skiltrix.abapproject')),
            ],
            options={
                'db_table': 'abap_source_files',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ABAPSubmission',
            fields=[
                ('submission_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source_code', models.TextField()),
                ('execution_mode', models.CharField(default='simulator', max_length=20)),
                ('verdict', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Syntax Error', 'Syntax Error'), ('Runtime Error', 'Runtime Error'), ('Time Limit Exceeded', 'Time Limit Exceeded')], max_length=30)),
                ('passed_tests', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='skiltrix.abapexercise')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'abap_submissions',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ABAPTestCase',
            fields=[
                ('test_case_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='skiltrix.abapexercise')),
            ],
            options={
                'db_table': 'abap_test_cases',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SAPSystemConnection',
            fields=[
                ('connection_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=100)),
                ('system_id', models.CharField(max_length=10)),
                ('client', models.CharField(default='100', max_length=5)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('auth_type', models.CharField(choices=[('basic', 'Basic Authentication (User/Password)'), ('oauth2_btp', 'SAP BTP OAuth 2.0 (Service Key)'), ('jwt_token', 'JWT Bearer Token')], default='basic', max_length=30)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('encrypted_password', models.TextField(blank=True)),
                ('btp_service_key_json', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('last_status_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sap_connections', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'sap_system_connections',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
