# Generated by Django 5.2.17 on 2026-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix', '0002_abapexercise_abaplearningprogress_abapproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abapdictionarytable',
            name='sample_records',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
