# Generated by Django 5.2.17 on 2026-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix', '0003_abapdictionarytable_sample_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abapsourcefile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='abapsourcefile',
            name='object_type',
            field=models.CharField(choices=[('report', 'Executable Report (PROG)'), ('include', 'ABAP Include (INCL)'), ('class', 'ABAP Class (CLAS)'), ('interface', 'ABAP Interface (INTF)'), ('function_module', 'Function Module (FUNC)'), ('ddic_table', 'Dictionary Table (TABL)'), ('structure', 'Dictionary Structure (STRU)'), ('folder', 'Folder Directory'), ('other', 'General File')], default='report', max_length=30),
        ),
    ]
