# Generated by Django 5.2.17 on 2026-10-04 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix', '0005_projectfile_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount (INR)')], max_length=10)),
                ('discount_value', models.PositiveIntegerField(help_text='Percent points or INR whole rupees')),
                ('compiler', models.CharField(default='abap', help_text='Compiler slug, or * for all', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('minimum_amount_paise', models.PositiveIntegerField(default=0)),
                ('maximum_discount_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skiltrix_compiler_coupon',
                'indexes': [models.Index(fields=['code', 'active'], name='skiltrix_co_code_9dbef6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompilerCouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiler', models.CharField(max_length=40)),
                ('discount_paise', models.PositiveIntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='skiltrix.compilercoupon')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'db_table': 'skiltrix_coupon_redemption',
                'indexes': [models.Index(fields=['coupon', 'user'], name='skiltrix_co_coupon__724587_idx')],
            },
        ),
    ]
