# Generated by Django 5.2.17 on 2026-10-04 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix', '0006_compilercoupon_compilercouponredemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('price_paise', models.PositiveIntegerField(default=29900)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('one_time_access', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skiltrix_compiler_product',
            },
        ),
        migrations.CreateModel(
            name='CompilerPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razorpay_order_id', models.CharField(max_length=80, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('base_amount_paise', models.PositiveIntegerField()),
                ('discount_paise', models.PositiveIntegerField(default=0)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='skiltrix.compilercoupon')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='compiler_payment_orders', to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='skiltrix.compilerproduct')),
            ],
            options={
                'db_table': 'skiltrix_compiler_payment_order',
            },
        ),
        migrations.AddField(
            model_name='compilercouponredemption',
            name='payment_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemption', to='skiltrix.compilerpaymentorder'),
        ),
        migrations.CreateModel(
            name='CompilerEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=12)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='compiler_entitlements', to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='skiltrix.compilerpaymentorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='skiltrix.compilerproduct')),
            ],
            options={
                'db_table': 'skiltrix_compiler_entitlement',
            },
        ),
        migrations.AddIndex(
            model_name='compilerpaymentorder',
            index=models.Index(fields=['user', 'status', 'created_at'], name='skiltrix_co_user_id_0a896c_idx'),
        ),
        migrations.AddConstraint(
            model_name='compilerpaymentorder',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_payment_idem_per_user'),
        ),
        migrations.AddIndex(
            model_name='compilerentitlement',
            index=models.Index(fields=['user', 'product', 'status'], name='skiltrix_co_user_id_54b78e_idx'),
        ),
        migrations.AddConstraint(
            model_name='compilerentitlement',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_compiler_entitlement_user_product'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('skiltrix', 'CompilerProduct').objects.using(schema_editor.connection.alias).get_or_create(
                slug='sap-abap', defaults={'name': 'SkilTrix SAP ABAP Compiler', 'price_paise': 29900, 'currency': 'INR', 'active': True, 'one_time_access': True}
            ),
            migrations.RunPython.noop,
        ),
    ]
