# Generated by Django 5.2.17 on 2026-10-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiltrix', '0007_compilerproduct_compilerpaymentorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilercoupon',
            name='allow_free',
            field=models.BooleanField(default=False, help_text='Allow this coupon to cover the full purchase without Razorpay'),
        ),
    ]
