# Generated by Django 5.2.17 on 2026-10-04 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('client_type', models.CharField(choices=[('public', 'Public Client (SPA / Mobile with PKCE)'), ('confidential', 'Confidential Client (Backend Server)')], default='public', max_length=20)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('allowed_redirect_uris', models.TextField(help_text='Newline or comma-separated list of allowed callback redirect URIs.')),
                ('allowed_logout_redirect_uris', models.TextField(blank=True, default='', help_text='Newline or comma-separated list of allowed post-logout redirect URIs.')),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Allowed CORS origin(s) for token exchange.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Application',
                'verbose_name_plural': 'Client Applications',
                'db_table': 'accounts_client_application',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('WARNING', 'Warning')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('client_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.clientapplication')),
            ],
            options={
                'verbose_name': 'Auth Audit Log',
                'verbose_name_plural': 'Auth Audit Logs',
                'db_table': 'accounts_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('otp_code', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'accounts_email_verification',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_password_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'accounts_password_reset',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=25)),
                ('bio', models.TextField(blank=True, default='')),
                ('email_verified', models.BooleanField(default=False)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'accounts_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.clientapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'accounts_user_session',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('code_challenge', models.CharField(max_length=255)),
                ('code_challenge_method', models.CharField(default='S256', max_length=10)),
                ('nonce', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(default='openid profile email', max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_auth_codes', to=settings.AUTH_USER_MODEL)),
                ('client_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='accounts.clientapplication')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='accounts.usersession')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'verbose_name_plural': 'Authorization Codes',
                'db_table': 'accounts_authorization_code',
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_revoked'], name='accounts_us_user_id_9aedac_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_89e160_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationcode',
            index=models.Index(fields=['code', 'is_used'], name='accounts_au_code_c22f88_idx'),
        ),
    ]
