# Generated by Django 5.2.15 on 2026-08-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'aaaab_chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('available_time', models.CharField(default=1, max_length=50)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'aaaab_product_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=12)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(default='user', max_length=10)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'aaaab_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField(default='Product')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('feature', models.BooleanField(default=0)),
                ('stock', models.IntegerField(default=1)),
                ('unit', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='aaaab.productcategory', to_field='category_id')),
            ],
            options={
                'db_table': 'aaaab_products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='productImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=50)),
                ('image_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='aaaab.products', to_field='product_id')),
            ],
            options={
                'db_table': 'aaaab_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='productsDetails', to='aaaab.products', to_field='product_id')),
            ],
            options={
                'db_table': 'aaaab_product_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='aaaab.products', to_field='product_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='aaaab.users', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaab_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(default=1, max_length=50)),
                ('sub_cat_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat_id', to='aaaab.productcategory', to_field='category_id')),
            ],
            options={
                'db_table': 'aaaab_sub_category',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(db_column='sub_cat_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='aaaab.subcategory', to_field='sub_cat_id'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_full', models.CharField(max_length=400)),
                ('default', models.BooleanField(default=0)),
                ('address_name', models.CharField(default='Address', max_length=40)),
                ('state', models.CharField(default='state', max_length=40)),
                ('city', models.CharField(default='city', max_length=50)),
                ('country', models.CharField(default='country', max_length=50)),
                ('phone', models.CharField(default='0', max_length=25)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('type', models.CharField(default='other', max_length=50)),
                ('address_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='aaaab.users', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaab_user_addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticket', models.TextField()),
                ('ticket_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to='aaaab.users', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaab_tickets',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='aaaab.users', to_field='user_id'),
        ),
        migrations.CreateModel(
            name='ProductRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('review', models.CharField(default=None, max_length=1000)),
                ('rating_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='productRatings', to='aaaab.products', to_field='product_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='users_rating', to='aaaab.users', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaab_product_ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_confirm', to='aaaab.orders', to_field='order_id')),
                ('address', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.CASCADE, related_name='address_confirm', to='aaaab.useraddress', to_field='address_id')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_confirm', to='aaaab.users', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaab_orders_confirm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aaaab.chat', to_field='chat_id')),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='aaaab.users', to_field='user_id')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='aaaab.users', to_field='user_id')),
            ],
            options={
                'db_table': 'aaaab_inchat',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_id_chat', to='aaaab.users', to_field='user_id'),
        ),
    ]
