# Generated by Django 5.2.15 on 2026-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiCart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cart_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'krishi_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiCrop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('water_need', models.CharField(max_length=20)),
                ('climate', models.CharField(max_length=30)),
                ('profit_min', models.IntegerField()),
                ('profit_max', models.IntegerField()),
                ('suitable_district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'krishi_crop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=50)),
                ('image_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'krishi_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiLiveMandi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=50)),
                ('commodity', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('modal_price', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'krishi_live_mandi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiProductAvailable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'krishi_product_available',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiProductDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=12)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'krishi_product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiProductRatings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('rating_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'krishi_product_ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'krishi_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrishiUsers1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=12)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(max_length=10)),
                ('is_verified', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('farm_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'krishi_users1',
                'managed': False,
            },
        ),
    ]
